matrix:
  include:
    - language: java
      jdk: openjdk8
      env:
        - python: "3.7"
      before_script:
        - cd backend
        - pip install -r requirements.txt
      script:
        - ./build

    - language: node_js
      before_script:
        - cd frontend
        - yarn install
      script:
        - yarn test
