matrix:
  include:
    - language: java
      jdk: openjdk8
      env: TOXENV=py37
        - python: 3.7
      dist: xenial
      addons:
        apt:
          packages:
            - python3-pip
      before_script:
        - cd backend
        - python3 --version
        - python3.7 -m pip install --upgrade pip
        - pip3 --version
        - pip3 install --user pipenv
        - pipenv install
      script:
        - ./build

    - language: node_js
      node_js: "8"
      before_script:
        - cd frontend
        - yarn install
      script:
        - yarn test
