matrix:
  include:
    - language: java
      jdk: openjdk8
      cache:
        directories:
          - $HOME/.m2
      dist: trusty
      sudo: true
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7-dev
            - python3-pip
      env:
        - global:
          - CODECOV_TOKEN="340bf0b8-91db-4593-a89f-b8a707cc56b7"
        - python: 3.7
      before_script:
        - cd backend
        - pip3 install --user --upgrade pip setuptools
        - pip3 install --user -r requirements.txt
      script:
        - ./build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      node_js: "8"
      cache: yarn
      env:
        - global:
          - CODECOV_TOKEN="340bf0b8-91db-4593-a89f-b8a707cc56b7"
      before_script:
        - cd frontend
        - yarn add codecov
        - yarn install
      script:
        - yarn test
        - yarn build
      after_success:
        - codecov
